config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to:"monitorings#index"
  resources :monitorings do
    collection do
      get 'lists'
    end
  end

  resources :temptations, except: [:index] do
    collection do
      get 'lists'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monitoring.rb
class Monitoring < ApplicationRecord
  validate :required_either_columns
  belongs_to :user
  encrypts :fact, :mind, :feel, :body, :behavior

  private

  def required_either_columns
    return if fact.present? || mind.present? || feel.present? || body.present? || behavior.present?
    errors.add(:base, 'Data is invalid')
  end
end

app/models/temptation.rb
class Temptation < ApplicationRecord
  validate :required_either_columns
  belongs_to :user
  encrypts :event, :talk, :cost, :get_out

  private

  def required_either_columns
    return if event.present? || talk.present? || cost.present? || get_out.present?
    errors.add(:base, 'Data is invalid')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'is invalid. Include both letters and numbers' }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :monitorings
  has_many :temptations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/monitorings_controller.rb
class MonitoringsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]
  before_action :set_monitoring, only: [:show, :edit]

  def index
  end

  def new
    @monitoring = Monitoring.new
  end

  def create
    @monitoring = Monitoring.new(monitoring_params)
    if @monitoring.save
      redirect_to lists_monitorings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @monitoring = Monitoring.find(params[:id])
    if @monitoring.update(monitoring_params)
      redirect_to lists_monitorings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    monitoring = Monitoring.find(params[:id])
    monitoring.destroy
    redirect_to lists_monitorings_path
  end

  def lists
    @monitorings = current_user.monitorings.order("created_at DESC")
  end

  private

  def monitoring_params
    params.require(:monitoring).permit(:fact, :mind, :feel, :body, :behavior).merge(user_id: current_user.id)
  end

  def move_to_index
    monitoring = Monitoring.find(params[:id])
    if current_user.id != monitoring.user.id
      redirect_to root_path
    end
  end

  def set_monitoring
    @monitoring = Monitoring.find(params[:id])
  end

end

app/controllers/temptations_controller.rb
class TemptationsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]
  before_action :set_temptation, only: [:show, :edit]

  def new
    @temptation = Temptation.new
  end

  def create
    @temptation = Temptation.new(temptation_params)
    if @temptation.save
      redirect_to lists_temptations_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @temptation = Temptation.find(params[:id])
    if @temptation.update(temptation_params)
      redirect_to lists_temptations_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    temptation = Temptation.find(params[:id])
    temptation.destroy
    redirect_to lists_temptations_path
  end

  def lists
    @temptations = current_user.temptations.order("created_at DESC")
  end

  private

  def temptation_params
    params.require(:temptation).permit(:event, :talk, :cost, :get_out).merge(user_id: current_user.id)
  end

  def move_to_index
    temptation = Temptation.find(params[:id])
    if current_user.id != temptation.user.id
      redirect_to root_path
    end
  end

  def set_temptation
    @temptation = Temptation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monitorings_helper.rb
module MonitoringsHelper
end

app/helpers/temptations_helper.rb
module TemptationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/744847be01.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">

  <body>
    <%= yield %>
  </body>
</html>

app/views/monitorings/_list.html.erb
<div class="monitor-list">
  <div class="monitor-list-upper">
    <div class="monitor-list__date"><%= list.created_at.strftime("%Y/%m/%d") %></div>
    <div class="monitor-list-more">
      <i class="fa-solid fa-chevron-down" style="color: #b9b9b9;"></i>
      <ul class="monitor-list-more__items">
        <%= link_to edit_monitoring_path(list.id) do %>
        <li><i class="fa-solid fa-pen" aria-hidden="true"></i> 編集</li>
        <% end %>
        <%= link_to monitoring_path(list.id), data:{ turbo_method: :delete } do %>
        <li><i class="fa-regular fa-trash-can" aria-hidden="true"></i> 削除</li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to monitoring_path(list.id) do %>
  <div class="monitor-list-content">
    <div class="monitor-list-item">状況</div>
    <div class="monitor-list-text"><%= list.fact %></div>
  </div>
  <div class="monitor-list-content">
    <div class="monitor-list-item">思考</div>
    <div class="monitor-list-text"><%= list.mind %></div>
  </div>
  <div class="monitor-list-content">
    <div class="monitor-list-item">感情</div>
    <div class="monitor-list-text"><%= list.feel %></div>
  </div>
  <% end %>
</div>

app/views/monitorings/_monitor-form.html.erb
<div class="monitor-main">
  <%= form_with model:monitoring, local: true do |f| %>
  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">状況</div>
    </div>
      <div class="monitor-info">どんなことがありましたか？</div>
    <%= f.text_area :fact, class:"monitor-text", placeholder:"" ,rows:"3" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">思考</div>
    </div>
      <div class="monitor-info">どんな考え/感覚/衝動が出てきましたか？</div>
    <%= f.text_area :mind, class:"monitor-text", placeholder:"" ,rows:"5" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">感情</div>
    </div>
      <div class="monitor-info">どんな感情でしたか？　例）喜び、好奇心、愛、怒り、恐れ、悲しみ、罪悪感、動揺、嫌悪</div>
    <%= f.text_area :feel, class:"monitor-text", id:"monitor-text__feel", placeholder:"" ,rows:"2" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">身体反応</div>
    </div>
      <div class="monitor-info">体にどんな反応がありましたか？　例）怒りで顔が熱い、恐怖で喉をしめつけられる</div>
    <%= f.text_area :body, class:"monitor-text", placeholder:"" ,rows:"2" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">行動</div>
    </div>
      <div class="monitor-info">出来事があった時、どんな行動をしましたか？　例）気まずさで周囲を見渡す、暴言を言う</div>
    <%= f.text_area :behavior, class:"monitor-text", placeholder:"" ,rows:"3" ,maxlength:"40000" %>
  </div>

  <div class="monitor-btn-contents">
    <%= f.submit "作成する" ,class:"monitor-btn" %>
  </div>
  <% end %>
</div>

app/views/monitorings/edit.html.erb
<%= render "monitorings/shared/header" %>
<%= render "monitorings/shared/header-margin" %>

<%= render partial: 'monitor-form', locals: { monitoring: @monitoring } %>

<%= render "monitorings/shared/footer" %>

app/views/monitorings/index.html.erb
<%= render "shared/header" %>


<div class="hero">
  <%= image_tag "hero.jpg", class:"hero-image" %>
  <div class="hero-info">
    <div class="hero-info__title">自分でできる心理療法</div>
    <div class="hero-info__message">
      ACT（アクセプタンス&コミットメント・セラピー）による<br>
      ストレスとの上手なつきあい方
    </div>
  </div>
</div>

<div class="main">
  <div class="main-menu">
    <div class="main-menu__square"></div>
    <div class="main-menu__title">エクササイズ</div>
  </div>
  <div class="main-contents">
    <div class="main-contents-wrapper">
      <div class="main-item__circle"></div>
      <div class="main-contents__title">悩みを受け止める</div>
    </div>
    <div class="main-contents-info">
      <div class="main-contents__text">
      いやなことがあった時、悩むのは当たり前です。<br>
      認知行動療法の「モニタリング」を使って、感情をメモに書き出してみましょう。
      </div>
      <%= link_to "エクササイズをする", new_monitoring_path, class:"main-contents__btn" %>
    </div>
  </div>
  <div class="main-contents">
    <div class="main-contents-wrapper">
      <div class="main-item__circle"></div>
      <div class="main-contents__title">厄介な思考に対処する</div>
    </div>
    <div class="main-contents-info">
      <div class="main-contents__text">
        習慣を手放したい時、新しいことをやる時。<br>
        人間は変化を避けるための理由を考えるのが得意です。<br>
        「理由づけ」マシンとなり、現状を変えられない、変えたくない理由を大量生産します。<br>
        厄介な思考と少し距離を置いて、うまく対処するためのスキルを身につけましょう。<br>
        <span style="font-size: 11px; color: #b9b9b9; font-style: italic;">
          出典）著:ラス・ハリス, 監訳:武藤 崇, よくわかるACT　明日からつかえるACT入門, 星和書店, 2012年
        </span>
      </div>

      <%= link_to "エクササイズをする", new_temptation_path, class:"main-contents__btn" %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/monitorings/lists.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<div class="monitor-lists" id="lists">
  <%= render partial: 'list', collection: @monitorings %>
</div>

app/views/monitorings/new.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<%= render partial: 'monitor-form', locals: { monitoring: @monitoring } %>

<%= render "shared/footer" %>

app/views/monitorings/show.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<div class="monitor-lists">
  <div class="monitor-list">
    <div class="monitor-list-upper">
      <div class="monitor-list__date"><%= @monitoring.created_at.strftime("%Y/%m/%d %H:%M") %></div>
      <div class="monitor-list-more">
        <i class="fa-solid fa-chevron-down" style="color: #b9b9b9;"></i>
        <ul class="monitor-list-more__items">
          <%= link_to edit_monitoring_path(@monitoring.id) do %>
          <li><i class="fa-solid fa-pen" aria-hidden="true"></i> 編集</li>
          <% end %>
          <%= link_to monitoring_path(@monitoring.id), data:{ turbo_method: :delete } do %>
          <li><i class="fa-regular fa-trash-can" aria-hidden="true"></i> 削除</li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">状況</div>
      <div class="monitor-list-text"><%= @monitoring.fact %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">思考</div>
      <div class="monitor-list-text"><%= @monitoring.mind %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">感情</div>
      <div class="monitor-list-text"><%= @monitoring.feel %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">身体反応</div>
      <div class="monitor-list-text"><%= @monitoring.body %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">行動</div>
      <div class="monitor-list-text"><%= @monitoring.behavior %></div>
    </div>
  </div>

  <%= link_to "一覧にもどる", lists_monitorings_path, class:"monitor-show__btn" %>
</div>

app/views/monitors/index.html.erb
<%= render "monitors/shared/header" %>


<div class="hero">
  <img class="hero-image" src="image/hero.jpg">
  <div class="hero-info">
    <div class="hero-info__title">自分でできる心理療法</div>
    <div class="hero-info__message">
      認知行動療法による<br>
      ストレスとの上手なつきあい方
    </div>
  </div>
</div>

<div class="main">
  <div class="main-contents">
    <div class="main-contents__square"></div>
    <div class="main-contents__title">エクササイズ</div>
  </div>
  <div class="main-monitor">
    <div class="main-monitor__title">悩みを受け止める</div>
    <div class="main-monitor__info">
      いやなことがあった時、悩むのは当たり前です。<br>
      認知行動療法である「モニタリング」を使って、感情をメモに書き出してみましょう。
    </div>
    <div class="main-monitor__btn">メモを書く</div>
  </div>
</div>

<%= render "monitors/shared/footer" %>

app/views/monitors/new.html.erb
<%= render "monitors/shared/header" %>


<div class="monitor-main">
  <%= form_with local: true do |f| %>
  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="monitor-circle"></div>
      <div class="monitor-item">状況</div>
    </div>
      <div class="monitor-info">どんなことがありましたか？</div>
    <%= f.text_area :hoge, class:"monitor-text", placeholder:"" ,rows:"3" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="monitor-circle"></div>
      <div class="monitor-item">思考</div>
    </div>
      <div class="monitor-info">どんな考え/感覚/衝動が出てきましたか？</div>
    <%= f.text_area :hoge, class:"monitor-text", placeholder:"" ,rows:"5" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="monitor-circle"></div>
      <div class="monitor-item">感情</div>
    </div>
      <div class="monitor-info">どんな感情でしたか？　例）喜び、愛、好奇心、怒り、悲しみ、</div>
    <%= f.text_area :hoge, class:"monitor-text", id:"monitor-text__feel", placeholder:"" ,rows:"2" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="monitor-circle"></div>
      <div class="monitor-item">身体反応</div>
    </div>
      <div class="monitor-info">体にどんな反応がありましたか？　例）怒りで顔が熱い、恐怖で喉をしめつけられる</div>
    <%= f.text_area :hoge, class:"monitor-text", placeholder:"" ,rows:"2" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="monitor-circle"></div>
      <div class="monitor-item">行動</div>
    </div>
      <div class="monitor-info">出来事があった時、どんな行動をしましたか？　例）気まずさで周囲を見渡す、暴言を言う</div>
    <%= f.text_area :hoge, class:"monitor-text", placeholder:"" ,rows:"3" ,maxlength:"40000" %>
  </div>

  <div class="monitor-btn-contents">
    <%= f.submit "作成する" ,class:"monitor-btn" %>
  </div>
  <% end %>
</div>


<%= render "monitors/shared/footer" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-title">自分でできる心理療法</div>
</div>

app/views/shared/_header-margin.html.erb
<div class="header-add-margin"></div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-main">
    <%=link_to "自分でできる心理療法", root_path, class:"header-title" %>
    <div class="navbar" id="navbar-items">
      <div class="navbar__lists">エクササイズ▼</div>
    </div>
    <div class="navbar" id="navbar-items02">
      <div class="navbar__lists">メモ一覧▼</div>
    </div>
  </div>
  <div class="header-user">
    <%if user_signed_in? %>
      <div class="user-logout">
        <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
      </div>
    <% else %>
      <div class="user-login">
        <%= link_to "ログイン", new_user_session_path %>
      </div>
      <div class="user-reg">
        <%= link_to "新規登録", new_user_registration_path %>
      </div>
    <% end %>
  </div>
  <ul class="navbar-memo hidden" id="navbar-pulldown">
    <%= link_to new_monitoring_path do %><li class="pulldown-list">悩みを受け止める</li><% end %>
    <%= link_to new_temptation_path do %><li class="pulldown-list">厄介な思考に対処する</li><% end %>
  </ul>
  <ul class="navbar-memo hidden" id="navbar-pulldown02">
    <%= link_to lists_monitorings_path do %><li class="pulldown-list">悩みを受け止める</li><% end %>
    <%= link_to lists_temptations_path do %><li class="pulldown-list">厄介な思考に対処する</li><% end %>
  </ul>
</div>

app/views/temptations/_form.html.erb
<div class="monitor-main">
  <%= form_with model:temptation, local: true do |f| %>
  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">状況</div>
    </div>
      <div class="monitor-info">思考に心を奪われた、日付/時間、きっかけになった出来事や状況を教えてください。</div>
    <%= f.text_area :event, class:"monitor-text", placeholder:"" ,rows:"3" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">頭の中のおしゃべり</div>
    </div>
      <div class="monitor-info">思考はあなたを夢中にさせようと、何を言いましたか？　何をしましたか？</div>
    <%= f.text_area :talk, class:"monitor-text", placeholder:"" ,rows:"5" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">自動操縦</div>
    </div>
      <div class="monitor-info">「自動操縦」とは、自分の行動に自覚的ではなく、思考にコントロールされている状態をいいます。<br>
        自動操縦で思考に夢中になった時、あなたの行動はどう変わりましたか？<br>
        そのためにどんな代償を払いましたか？</div>
    <%= f.text_area :cost, class:"monitor-text", id:"monitor-text__feel", placeholder:"" ,rows:"5" ,maxlength:"40000" %>
  </div>

  <div class="monitor-contents">
    <div class="monitor-wrapper">
      <div class="item-circle"></div>
      <div class="monitor-item">抜け出す方法</div>
    </div>
      <div class="monitor-info">その状態から抜け出すことはできましたか？　どうやって抜け出しましたか？</div>
    <%= f.text_area :get_out, class:"monitor-text", placeholder:"" ,rows:"5" ,maxlength:"40000" %>
  </div>

  <div class="monitor-btn-contents">
    <%= f.submit "作成する" ,class:"monitor-btn" %>
  </div>
  <% end %>
</div>

app/views/temptations/_list.html.erb
<div class="monitor-list">
  <div class="monitor-list-upper">
    <div class="monitor-list__date"><%= list.created_at.strftime("%Y/%m/%d") %></div>
    <div class="monitor-list-more">
      <i class="fa-solid fa-chevron-down" style="color: #b9b9b9;"></i>
      <ul class="monitor-list-more__items">
        <%= link_to edit_temptation_path(list.id) do %>
        <li><i class="fa-solid fa-pen" aria-hidden="true"></i> 編集</li>
        <% end %>
        <%= link_to temptation_path(list.id), data:{ turbo_method: :delete } do %>
        <li><i class="fa-regular fa-trash-can" aria-hidden="true"></i> 削除</li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to temptation_path(list.id) do %>
  <div class="monitor-list-content">
    <div class="monitor-list-item">思考に心を奪われた状況</div>
    <div class="monitor-list-text"><%= list.event %></div>
  </div>
  <div class="monitor-list-content">
    <div class="monitor-list-item">思考はあなたを夢中にさせようと、何を言いましたか？</div>
    <div class="monitor-list-text"><%= list.talk %></div>
  </div>
  <% end %>
</div>

app/views/temptations/edit.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<%= render partial: 'form', locals: { temptation: @temptation} %>

<%= render "shared/footer" %>

app/views/temptations/lists.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<div class="monitor-lists" id="lists">
  <%= render partial: 'list', collection: @temptations %>
</div>

app/views/temptations/new.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<%= render partial: 'form', locals: { temptation:@temptation } %>

<%= render "shared/footer" %>

app/views/temptations/show.html.erb
<%= render "shared/header" %>
<%= render "shared/header-margin" %>

<div class="monitor-lists">
  <div class="monitor-list">
    <div class="monitor-list-upper">
      <div class="monitor-list__date"><%= @temptation.created_at.strftime("%Y/%m/%d %H:%M") %></div>
      <div class="monitor-list-more">
        <i class="fa-solid fa-chevron-down" style="color: #b9b9b9;"></i>
        <ul class="monitor-list-more__items">
          <%= link_to edit_temptation_path(@temptation.id) do %>
          <li><i class="fa-solid fa-pen" aria-hidden="true"></i> 編集</li>
          <% end %>
          <%= link_to temptation_path(@temptation.id), data:{ turbo_method: :delete } do %>
          <li><i class="fa-regular fa-trash-can" aria-hidden="true"></i> 削除</li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">思考に心を奪われた状況</div>
      <div class="monitor-list-text"><%= @temptation.event %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">思考はあなたを夢中にさせようと、何を言いましたか？　何をしましたか？</div>
      <div class="monitor-list-text"><%= @temptation.talk %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">思考に夢中になった時、あなたの行動はどう変わりましたか？<br>
        そのためにどんな代償を払いましたか？</div>
      <div class="monitor-list-text"><%= @temptation.cost %></div>
    </div>
    <div class="monitor-list-content">
      <div class="monitor-list-item">その状態から抜け出すことはできましたか？　どうやって抜け出しましたか？</div>
      <div class="monitor-list-text"><%= @temptation.get_out %></div>
    </div>
  </div>

  <%= link_to "一覧にもどる", lists_temptations_path, class:"monitor-show__btn" %>
</div>